/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dal;

import context.DBContext;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import model.Car;
import model.User;

/**
 *
 * @author MinHeee
 */
public class AppointmentByAI extends DBContext {

    public List<Car> getCarsWithCustomerInfo() {
        List<Car> list = new ArrayList<>();
        String sql = "SELECT U.FullName AS CustomerName, "
                + "C.CarID, (C.Brand + ' ' + C.Model + ' - ' + C.LicensePlate) AS CarInfo "
                + "FROM Users U "
                + "INNER JOIN Cars C ON U.UserID = C.OwnerID "
                + "ORDER BY U.FullName, CarInfo";

        try (PreparedStatement ps = connection.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Car car = new Car();
                car.setCarId(rs.getInt("CarID"));
                // Gán chuỗi CarInfo vào brand để dễ dùng trong JSP
                car.setBrand(rs.getString("CarInfo"));

                // Gán tên khách hàng vào owner
                User owner = new User();
                owner.setFullName(rs.getString("CustomerName"));
                car.setOwner(owner);

                list.add(car);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return list;
    }

    public boolean addAppointmentInTwoHours(int carId, int createdByUserId, int requestedPackageId, String notes) {

        // 1. Chuẩn bị câu lệnh SQL
        String sql = "INSERT INTO Appointments "
                + " (CarID, AppointmentDate, RequestedPackageID, Notes, CreatedBy, Status)"
                + " VALUES (?, ?, ?, ?, ?, ?)";

        // 2. ✅ Lấy thời gian hiện tại và cộng thêm 2 tiếng
        LocalDateTime appointmentTime = LocalDateTime.now().plusHours(2);

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            // 4. Set các tham số
            ps.setInt(1, carId);

            // Sử dụng setObject để truyền thẳng đối tượng LocalDateTime vào
            // JDBC Driver sẽ tự động chuyển nó sang kiểu DATETIME2 của SQL Server
            ps.setObject(2, appointmentTime);

            // Xử lý nếu không có gói nào được chọn
            if (requestedPackageId == 0) {
                ps.setNull(3, java.sql.Types.INTEGER);
            } else {
                ps.setInt(3, requestedPackageId);
            }

            ps.setString(4, notes);
            ps.setInt(5, createdByUserId);
            ps.setString(6, "PENDING"); // Trạng thái ban đầu

            // 5. Thực thi
            int rowsAffected = ps.executeUpdate();

            // Trả về true nếu có 1 dòng được thêm vào
            return rowsAffected > 0;

        } catch (SQLException e) {
            e.printStackTrace(); // Ghi log lỗi
            return false;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Quick booking: create appointment for selected car in 2 hours. Used when
     * user clicks quick action button in AI widget.
     *
     * @param carId the car to book
     * @param createdByUserId the user creating the appointment
     * @return true if successful
     */
    // Create appointment in two hours using provided notes (e.g., generated by Gemini)
    public boolean createAppointmentInTwoHours(int carId, int createdByUserId, String notes) {
        String sql = "INSERT INTO Appointments "
                + "(CarID, AppointmentDate, RequestedServices, Status, Notes, CreatedBy, CreatedDate, RequestedPackageID) "
                + "VALUES (?, ?, NULL, ?, ?, ?, ?, 6)";

        LocalDateTime appointmentTime = LocalDateTime.now().plusHours(2);
        java.sql.Timestamp createdDate = new java.sql.Timestamp(System.currentTimeMillis());

        try (PreparedStatement ps = connection.prepareStatement(sql)) {

            ps.setInt(1, carId);
            ps.setObject(2, appointmentTime);
            ps.setString(3, "PENDING");
            ps.setString(4, notes == null ? "Quick booking from AI" : notes);
            ps.setInt(5, createdByUserId);
            ps.setTimestamp(6, createdDate);

            int rows = ps.executeUpdate();
            return rows > 0;

        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Fetch active maintenance packages with pricing info
     *
     * @return List of Maps with PackageCode, BasePrice (GiaGoc), FinalPrice
     * (GiaCuoiCung)
     */
    public List<java.util.Map<String, Object>> getActivePackagePrices() {
        List<java.util.Map<String, Object>> list = new ArrayList<>();
        String sql = "SELECT PackageCode, BasePrice AS GiaGoc, FinalPrice AS GiaCuoiCung "
                + "FROM MaintenancePackage "
                + "WHERE IsActive = 1 "
                + "ORDER BY DisplayOrder, FinalPrice";

        try (PreparedStatement ps = connection.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                java.util.Map<String, Object> pkg = new java.util.HashMap<>();
                pkg.put("packageCode", rs.getString("PackageCode"));
                pkg.put("basePrice", rs.getDouble("GiaGoc"));
                pkg.put("finalPrice", rs.getDouble("GiaCuoiCung"));
                list.add(pkg);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return list;
    }

}
